name: Build SFA

on:
  workflow_dispatch:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      telegram: ${{ steps.set-var.outputs.telegram }}
    steps:
      - name: Set Variables
        id: set-var
        if: contains(github.event.head_commit.message, '(Push)')
        run: |
          echo "telegram=enable" >> $GITHUB_OUTPUT

  go:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.go.outputs.version}}
    steps:
      - name: get latest go version
        id: go
        run: |
          echo version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/update-versions-manifest-file/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

  sing-box:
    runs-on: ubuntu-latest
    needs: go
    outputs:
      version: ${{steps.sing-box.outputs.version}}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v7
        with:
          go-version: ${{needs.go.outputs.version}}

      - name: get sing-box version
        id: sing-box
        run: |
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          echo version=$version >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - go
      - sing-box
    outputs:
      tags: ${{ env.TAGS }}
    env:
      VERSION: ${{ needs.sing-box.outputs.version }}
      TAGS: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_acme,with_clash_api,with_tailscale,with_ccm,with_ocm,with_cloudflared,with_usbip,with_openvpn,with_openconnect,badlinkname,tfogo_checklinkname0
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ needs.go.outputs.version }}

      - name: checkout app repository
        uses: actions/checkout@v5
        with:
          path: sfa
          repository: jasmoli/sing-box-for-android
          ref: 'dev-xireiki'
          submodules: recursive

      - name: setup java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 17

      - name: setup ndk
        uses: nttld/setup-ndk@v1.6.0
        id: setup-ndk
        with:
          ndk-version: r28c

      - name: get latest build tools version
        id: sdk
        run: echo version=$(ls $ANDROID_HOME/build-tools | tail -n 1) >> $GITHUB_OUTPUT

      - name: build libbox
        env:
          CC: ${{steps.setup-ndk.outputs.ndk-path}}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang
          CGO_ENABLED: '0'
        run: |
          make lib_install
          gomobile bind -v -a -trimpath -buildvcs=false -androidapi 21 -javapkg=io.nekohasekai -libname=box -tags ${TAGS} -ldflags "-checklinkname=0 -X github.com/sagernet/sing-box/constant.Version=${VERSION} -s -w -buildid=" ./experimental/libbox

      - name: setup build env && build app
        env:
          KEYSTORE: ${{secrets.SIGN_KEY}}
          ALIAS_NAME: ${{secrets.ALIAS}}
          KEYSTORE_PASS: ${{secrets.SIGN_KEY}}
        run: |
          mkdir -p sfa/app/libs/
          cp ./libbox.aar sfa/app/libs/
          cd sfa
          echo "" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC" >> gradle.properties
          echo "org.gradle.caching=true" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "android.lint.checkReleaseBuilds=false" >> gradle.properties
          echo "VERSION_NAME=${VERSION}" > version.properties
          echo "VERSION_CODE=$(date +%Y%m%d%H)" >> version.properties
          sed -i '/signingConfig = signingConfigs.getByName("release")/d' app/build.gradle.kts
          chmod +x ./gradlew
          ./gradlew :app:clean :app:assembleOtherRelease && ./gradlew --stop

      - name: sign app
        uses: xireiki/sign-android-release@v2
        env:
          BUILD_TOOLS_VERSION: ${{steps.sdk.outputs.version}}
        with:
          alias: ${{secrets.ALIAS}}
          releaseDirectory: sfa/app/build/outputs/apk/other/release
          signingKeyBase64: ${{secrets.SIGN_KEY}}
          keyStorePassword: ${{secrets.KEY_STORE_PASSWORD}}

      - name: upload arm64-v8a apk
        uses: actions/upload-artifact@v7
        with:
          name: sfa-${{env.VERSION}}-arm64-v8a
          path: sfa/app/build/outputs/apk/other/release/*-arm64-v8a-signed.apk
          compression-level: 9

      - name: upload armeabi-v7a apk
        uses: actions/upload-artifact@v7
        with:
          name: sfa-${{env.VERSION}}-armeabi-v7a
          path: sfa/app/build/outputs/apk/other/release/*-armeabi-v7a-signed.apk
          compression-level: 9

      - name: upload x86_64 apk
        uses: actions/upload-artifact@v7
        with:
          name: sfa-${{env.VERSION}}-x86_64
          path: sfa/app/build/outputs/apk/other/release/*-x86_64-signed.apk
          compression-level: 9

      - name: upload x86 apk
        uses: actions/upload-artifact@v7
        with:
          name: sfa-${{env.VERSION}}-x86
          path: sfa/app/build/outputs/apk/other/release/*-x86-signed.apk
          compression-level: 9

      - name: upload universal apk
        uses: actions/upload-artifact@v7
        with:
          name: sfa-${{env.VERSION}}-universal
          path: sfa/app/build/outputs/apk/other/release/*-universal-signed.apk
          compression-level: 9

  post:
    runs-on: ubuntu-latest
    needs:
      - build
      - prepare
    if: ${{ needs.prepare.outputs.telegram == 'enable' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set Post Info
        if: contains(github.event.head_commit.message, '(Push)')
        id: set-post-info
        env:
          singBoxVersion: ${{ needs.sing-box.outputs.version }}
          goVersion: ${{ needs.go.outputs.version }}
          tags: ${{ needs.build.outputs.tags }}
        run: |
          {
            echo 'CONTEXT<<EOF'
            echo -e "sing-box for android ${singBoxVersion}\n\nEnvironment: go v${goVersion}\nTags: ${tags}\n\ncommit: ${{ github.event.head_commit.message }}\n$(git log --oneline -n 9 --no-decorate | sed 's/^[0-9a-f]* //' | sed 's/^/ - /' | sed 's/^ - Build.*//')"
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Rename and Remove Directory
        run: |
          find . -name 'SFA-*.apk' -exec mv {} . \;
          find . -maxdepth 1 -type d -empty -delete

      - name: Post to channel
        uses: xireiki/channel-post@v1
        with: 
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          path: SFA-*
          context: ${{ steps.set-post-info.outputs.CONTEXT }}
          parse_mode: HTML
          large_file: true
          api_id: ${{ secrets.API_ID }}
          api_hash: ${{ secrets.API_HASH }}
          method: sendFile
